name: build

on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install --prefer-offline --no-audit
      - name: Run lint
        run: npm run lint

  build-and-push:
    needs: [lint]
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag website:latest
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3.6.0
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push image to github
      run: |
        IMAGE_NAME="website:latest"
        IMAGE_ID="ghcr.io/${GITHUB_REPOSITORY_OWNER}/website:latest"
        IMAGE_ID=$(echo "$IMAGE_ID" | tr '[:upper:]' '[:lower:]')
        echo "IMAGE_ID=$IMAGE_ID"
        docker tag "$IMAGE_NAME" "$IMAGE_ID"
        docker push "$IMAGE_ID"
